---
title: "SPY_RSI_stochslow_backtest"
author: "Collin"
date: "9/1/2021"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(quantmod)
library(httr)
library(jsonlite)
library(TTR)
library(zoo)
library(chron)

library(writexl)
```




```{r}
#initialize taapi token into Renviron file
readRenviron(".Renviron")
Sys.getenv("MARKETSTACK_TOKEN")
```


```{r}
#test query the API


call_received = GET(str_glue("https://cloud.iexapis.com/stable/stock/spy/chart/date/{date}?token={YOUR_TOKEN_HERE}",
             date = "20210901",                
             YOUR_TOKEN_HERE = Sys.getenv("IEX_TOKEN")))

price_data = content(call_received,type = "text") %>% 
  fromJSON()

price_data
high_low_close = price_data %>% 
  select(date,minute = label,high,low,close)







  


```

#start here
```{r}

high_low_close %>% 
  mutate(highest_high_14 = rollmax(high,5,align = "center"))


```


#Using Alpha Vantage API
```{r}
#Call the API
stoch_call = GET(str_glue("https://www.alphavantage.co/query?function=STOCH&symbol={symbol}&interval=1min&apikey={key}&fastkperiod=14&slowdperiod=3",
                          symbol = "SPY", key = Sys.getenv("ALPHA_VANTAGE_KEY")))

stoch_call
#format properly
stochastic_data = content(stoch_call, type = "text") %>% 
  fromJSON()

stochastic_data
stochastic_data = stochastic_data$`Technical Analysis: STOCH` %>% 
  as.tibble() 
stochastic_data


p="[0-9]{4}-[0-9]{2}-[0-9]{2}"
time_extract = "\\s[0-9]{2}:[0-9]{2}"
stochastic_data = stochastic_data %>% unnest() %>% 
  mutate(stochastic = rep_len(c("SlowD", "SlowK"), length.out = 2)) %>% 
  pivot_longer(cols = -stochastic, names_to = "time", values_to = "stochastic_values") %>% 
  arrange(time) %>% 
  mutate(date = ymd_hm(time)) %>% 
  pivot_wider(names_from = stochastic,values_from = stochastic_values) %>% 
  filter(date >= "2021-09-01") %>% 
  arrange(time)



stochastic_data %>% 
  mutate(date = format(time, tz="America/Los_Angeles"))

   
 


```
#Using EOD API
```{r}
eod_call = GET(str_glue("https://www.alphavantage.co/query?function=STOCH&symbol={symbol}&interval=1min&apikey={key}&fastkperiod=14&slowdperiod=3",
                          symbol = "SPY", key = Sys.getenv("ALPHA_VANTAGE_KEY")))


```


#using sample text file
```{r}

#
spy_data <- read_csv("SPY_5mintxt", col_names = FALSE)
spy_data = spy_data %>% 
  select(date = X1, open = X2, high = X3, low = X4, close = X5, volume = X6)

spy_data %>% 
  write_xlsx(path = "/Users/collinkennedy/Dropbox/finance/spy_data.xlsx")
  
```

#using marketstack data
```{r}
mktwatch_call =GET(str_glue("http://api.marketstack.com/v1/intraday/2021-09-01?access_key={key}&symbols={symbol}&exchange=NYSE&interval={interval}&sort=ASC",
                             key = Sys.getenv("MARKETSTACK_TOKEN"),
                            interval = "1min",
                             symbol = "SPY"))

mktwatch = content(mktwatch_call, type = "text") %>% 
  fromJSON()

#store the dataframe the returned list as a tibble
mktstack = mktwatch[2]$data %>% 
  as.tibble()

mktstack %>% 
  mutate(date = as_datetime(gsub("+0000","",date),tz = "America/Los_Angeles")) %>% 
  arrange(date)


?as_datetime

```





